# Generated by Django 5.1 on 2024-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBaseInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_name', models.CharField(max_length=10, unique=True, verbose_name='昵称')),
                ('user_pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('tel_number', models.CharField(max_length=11, unique=True, verbose_name='注册手机号')),
                ('gender', models.IntegerField(choices=[(0, 'secret'), (1, 'man'), (2, 'female')], default=0, verbose_name='性别')),
                ('user_id', models.CharField(max_length=20, verbose_name='用户唯一标识ID')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='个性签名')),
            ],
            options={
                'verbose_name': '用户基本信息',
                'verbose_name_plural': '用户基本信息',
                'db_table': 't_user_base_info',
            },
        ),
    ]
