# Generated by Django 5.1 on 2024-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbaseinfomodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar/%Y/%m/%d/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userbaseinfomodel',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='userbaseinfomodel',
            name='gender',
            field=models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
    ]
